// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UefaRankingApplication.DataAccess.DbContexts;

#nullable disable

namespace UefaRankingApplication.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class TeamDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UefaRankingApplication.Data.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActiveTeamsNumber")
                        .HasColumnType("int")
                        .HasColumnName("ActiveTeamsNumber");

                    b.Property<int>("AllTeamsNumber")
                        .HasColumnType("int")
                        .HasColumnName("AllTeamsNumber");

                    b.Property<int>("CountryPoints")
                        .HasColumnType("int")
                        .HasColumnName("CountryPoints");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Name");

                    b.Property<int>("RankingPosition")
                        .HasColumnType("int")
                        .HasColumnName("RankingPosition");

                    b.HasKey("Id");

                    b.ToTable("Country");
                });

            modelBuilder.Entity("UefaRankingApplication.Data.Models.CountryTeamsMap", b =>
                {
                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<int>("UniqueConnectionValue")
                        .HasColumnType("int");

                    b.HasIndex("CountryId");

                    b.HasIndex("TeamId");

                    b.ToTable("CountryTeamMap");
                });

            modelBuilder.Entity("UefaRankingApplication.Data.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("Result");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int");

                    b.Property<int>("Team_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Match");
                });

            modelBuilder.Entity("UefaRankingApplication.Data.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Country_Id")
                        .HasColumnType("int");

                    b.Property<int?>("GroupPoints")
                        .HasColumnType("int")
                        .HasColumnName("GroupPoints");

                    b.Property<bool>("IsPlaying")
                        .HasColumnType("bit")
                        .HasColumnName("IsPlaying");

                    b.Property<int?>("MatchId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Name");

                    b.Property<int>("RankingPoints")
                        .HasColumnType("int")
                        .HasColumnName("RankingPoints");

                    b.HasKey("Id");

                    b.HasIndex("Country_Id");

                    b.HasIndex("MatchId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("UefaRankingApplication.Data.Models.CountryTeamsMap", b =>
                {
                    b.HasOne("UefaRankingApplication.Data.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UefaRankingApplication.Data.Models.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("UefaRankingApplication.Data.Models.Match", b =>
                {
                    b.HasOne("UefaRankingApplication.Data.Models.Team", null)
                        .WithMany("Matches")
                        .HasForeignKey("TeamId");
                });

            modelBuilder.Entity("UefaRankingApplication.Data.Models.Team", b =>
                {
                    b.HasOne("UefaRankingApplication.Data.Models.Country", "Country")
                        .WithMany("Teams")
                        .HasForeignKey("Country_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UefaRankingApplication.Data.Models.Match", null)
                        .WithMany("Teams")
                        .HasForeignKey("MatchId");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("UefaRankingApplication.Data.Models.Country", b =>
                {
                    b.Navigation("Teams");
                });

            modelBuilder.Entity("UefaRankingApplication.Data.Models.Match", b =>
                {
                    b.Navigation("Teams");
                });

            modelBuilder.Entity("UefaRankingApplication.Data.Models.Team", b =>
                {
                    b.Navigation("Matches");
                });
#pragma warning restore 612, 618
        }
    }
}
